@WebAPI_HostAddress = http://localhost:5100

GET {{WebAPI_HostAddress}}/weatherforecast/
Accept: application/json
Authorization:Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXJuYW1lIiwibmJmIjoxNzQ3NDM5NjY1LCJleHAiOjE3NDc0NDMyNjUsImlhdCI6MTc0NzQzOTY2NSwiaXNzIjoieW91ci1pc3N1ZXIiLCJhdWQiOiJ5b3VyLWF1ZGllbmNlIn0.Pmxk6-Un9fitw6hzhKea3Uama04wFV1H26AGhPqjUHMPfaQPsmcIjIrpWN1fgjAmjEMWjUviAHz0tmZEKYyv2M64Hy-2ik021S58xRW1r2qPZ0SGtznuN8-LVyvUHTYLBSiczN8x5ZlPL8RN7G6Mcp_-kgcP8YQ5ijvob2G8i01a_6l7U2mbJ0S8iZYH3Cz0ab8v0mzsb2_BWBAsbPHdOxT0N01PVDzWJwszKEFxQAvESKRN6oQZVpR62nf1kFJYDcOvKRJLtGnJkFEQ_uOoGyAlMvIFhP6k_6Ks2v9FkDAiE4lbZGE7FRZs5Xjw_AlOnFM-yF9Z0XR8dY0_rKVI_g
###
